# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

destination: public
source: src

title: kmapper
company: kmapper GmbH
hr_number: CHE-409.729.612
hr_place: Basel-Stadt

email: mail@kmapper.com
email_cyrill: cyrill.martin@kmapper.com
telephone: +41 79 745 62 05
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kmapper.com" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: sites
collections: 
  de:
    output: true
    permalink: /:collection/:name/
  en:
    output: true
    permalink: /:collection/:name/

defaults: 
  - scope:
      path: ""
      type: "de"
    values:
      lang: "de"
  - scope:
      path: ""
      type: "en"
    values:
      lang: "en"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gradients.scss
